In [4]:
# pip install numpy

In [3]:
import numpy as np

In [5]:
a = np.array([2,5,7,8,9,10])
print(a)
print(type(a))
print(a.shape)

[ 2  5  7  8  9 10]
<class 'numpy.ndarray'>
(6,)


In [6]:
a = np.array([[2],[5],[7],[8],[9],[10]])
print(a)
print(type(a))
print(a.shape)

[[ 2]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]]
<class 'numpy.ndarray'>
(6, 1)


In [11]:
# create zeroes, Ones, Custom Array

a = np.zeros((3,3))
print(a)

b = np.ones((3,3))
print(b)

c = np.full((3,2),5)
print(c)


# Identity Matrix
d = np.eye(4)
print(d)

# Random Matrix
randomMat = np.random.random((2,3))
print(randomMat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.48434148 0.64417402 0.09022885]
 [0.5514854  0.22730605 0.38919856]]


In [16]:
print(randomMat[ 1,-2])

0.22730604726598325


In [17]:
print(randomMat[ 1,:])

[0.5514854  0.22730605 0.38919856]


In [19]:
# Datatypes
a1 = np.zeros((3,3))

print(a1.dtype)

float64


In [21]:
a1 = np.zeros((3,3), dtype = int)

print(a1.dtype)

int32


In [22]:
# Mathematical Operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [23]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [24]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [25]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
# Matrix Multiplication / Dot Products

print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [27]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [40]:
# Multiplication of Vector => Scalar
a = np.array([1,2,3,4,])
b = np.array([1,2,3,4,])
print(a.dot(b))

30


In [41]:
print(x)
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [42]:
# Stacking of arrays

print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [43]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [44]:
a = np.stack((a,b),axis=0)

In [45]:
# Reshape a numpy array
print("Original: ",a)
a = a.reshape((4,2))   #if you don't know what shape to allot just use (-1,2) or (4,-1)
print("Modified",a)

Original:  [[ 1  2  3  4]
 [ 1  4  9 16]]
Modified [[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [49]:
a = np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [62]:
np.random.shuffle(a)
print(a)

[ 6 13  9  8  7  5 11 10 14 12]


In [66]:
# Random Matrix

a = np.random.rand(2,3)
a

array([[-0.27348302,  0.00381211, -0.04001415],
       [-1.69768934,  2.38613388,  2.34344692]])

In [67]:
a = np.random.randn(2,3)
a

array([[-0.36193119,  0.83200601,  0.92654098],
       [-0.10310482, -1.32446395, -0.57805024]])

In [70]:
a = np.random.randint(2,10,5)   #(start,end,count)
a

array([7, 9, 8, 4, 7])

In [81]:
# Randomly pick one element from a array
element = np.random.choice([1,4,5,6,7,7,32,22,346])
print(element)

1


In [94]:
# Replicate(Store the state)
np.random.seed(4)
np.random.shuffle(a)
print(a)

[8 7 4 9 7]


In [101]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
1
[1 2 3 4]
[1 5]


In [104]:
c = np.array([1,5,4,2,0])

#Median
print(np.median(c))

#Mean
print(np.mean(c))

#weights
w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))


w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))




2.0
2.4
2.066666666666667
2.4


In [108]:
# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)


#InBuilt func
dev = np.std(c)
print(dev)

#variance
print(myStd**2)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
