In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
df = pd.read_csv('D:\Projects\TCE\TCE\Movie Review Classification\Dataset\Train.csv')
df

review label
0   mature intelligent and highly charged melodram...   pos
1   http://video.google.com/videoplay?docid=211772...   pos
2   Title: Opera (1987) Director: Dario Argento Ca...   pos
3   I think a lot of people just wrote this off as...   pos
4   This is a story of two dogs and a cat looking ...   pos
5   Steve Carell comes into his own in his first s...   pos
6   I'm only going to write more because it's requ...   neg
7   OK, it was a "risky" move to rent this flick, ...   neg
8   Cannibalism, a pair of cinematic references to...   pos
9   This is one of the great modern kung fu films....   pos
10  Steve Martin looks like he's had a face lift. ...   neg
11  Robert Jordan is a television star. Robert Jor...   pos
12  Probably the best comedy in a long time. keeps...   pos
13  The earlier review is pretty much on target, w...   neg
14  It is depressing that many people don't unders...   pos
15  This, like Murder She Wrote, is one of those s...   pos
16  This film is a sleeper because Rod Steiger's i...   pos
17  Give director Stanley Tong of Jackie Chan's Su...   neg
18  This is another of my favorite Columbos. It sp...   pos
19  This film IS brilliant...... without a doubt. ...   pos
20  "Soul Plane" is a horrible attempt at comedy t...   neg
21  "Party Girl" capitalizes on the tremendous cha...   pos
22  I haven't seen so many people packed outside a...   pos
23  Kevin Spacey is without a doubt one of the bes...   neg
24  i love this film!! maybe it is my generation b...   pos
25  The first time I saw this film I was a kid. I ...   pos
26  This movie is simply awesome. It is so hilario...   pos
27  This movie was horrible. I swear they didn't e...   neg
28  Two things can happen when an ensemble cast is...   pos
29  This is such a revered and studied film, a cla...   pos
30  Silly comedy casts an embarrassed-seeming Ray ...   neg
31  So far Miguel Bardem's career it's been one of...   pos
32  First of all, this movie reminded me of the ol...   neg
33  Every high praise word fell way short before t...   pos
34  This film should have been fun. A young Lea Th...   neg
35  This was an incredibly stupid movie. It was po...   neg
36  The movie opens upon Julian Sands, lying on hi...   neg
37  Prom Night 2 is an OK horror movie but prom ni...   neg
38  It would be quite easy to make this movie soun...   neg
39  Let me see...I've seen every film Lou Ferrigno...   neg
40  Not so many people like the movies of Bertrand...   pos
41  I suspect there's some revisionist history goi...   pos
42  I had to walk out on this film fifteen minutes...   neg

In [9]:
X = df['review']
Y = df['label']
Y = Y.map({'pos':1,'neg':0})

In [10]:
# cleaning the data 
import clean_text as ct 
x_clean = [ct.getStemmedReview(i) for i in X]
cv = CountVectorizer()
x_vec = cv.fit_transform(x_clean).toarray()
print(x_vec)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB
mnb = MultinomialNB()
mnb.fit(x_vec,Y)

MultinomialNB()

In [15]:
df_test = pd.read_csv('D:\Projects\TCE\TCE\Movie Review Classification\Dataset\Test.csv')
X_test = df_test['review']
x_test_clean = [ct.getStemmedReview(i) for i in X_test]
cv = CountVectorizer()
x_test_vec = cv.fit_transform(x_test_clean).toarray()
print(x_test_vec)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
mnb.score(x_vec,Y)

1.0

In [16]:
mnb.predict(x_test_vec)

ValueError: X has 36289 features, but MultinomialNB is expecting 1895 features as input.