In [58]:
# if we put () after some keywords its a function like type()
# if we don't the it is a attribute

In [59]:
import numpy as np

In [60]:
a = np.array([1,2,3,4,5])
print(type(a))
print(a.shape)
print(a)
a

<class 'numpy.ndarray'>
(5,)
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [61]:
b = np.array([[1],[2],[3],[4]])
print(type(b))
print(b.shape)
print(b)
b

<class 'numpy.ndarray'>
(4, 1)
[[1]
 [2]
 [3]
 [4]]


array([[1],
       [2],
       [3],
       [4]])

In [62]:
print(b[1][0])

2


In [63]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [64]:
# create zeros, ones, custom array
a = np.zeros((3,3))
print(a)
b = np.ones((2,3))
print(b)
c = np.full((3,2),5)  # ((array dimentions), constant)
print(c)

#identity matrix- size/Square matrix
d = np.eye(4)
print(d)

#random matrix
randommat = np.random.random((2,3))
print(randommat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.90618188 0.69827795 0.59488639]
 [0.28557784 0.02744199 0.46780696]]


In [65]:
print(randommat[1,:])
print(randommat[:,1])
print(randommat[1,1:])

randommat[1,1:3] = 1 #slicing
print(randommat)

[0.28557784 0.02744199 0.46780696]
[0.69827795 0.02744199]
[0.02744199 0.46780696]
[[0.90618188 0.69827795 0.59488639]
 [0.28557784 1.         1.        ]]


In [66]:
# datatypes
print(c.dtype)

# we can change the dtype of an array by
c = np.full((3,2),5, dtype = np.float64)
print(c.dtype)

int64
float64


In [67]:
#Mathematical operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(np.add(x,y))
print(np.subtract(x,y)) # x-y
print(np.multiply(x,y)) # x*y
print(np.divide(x,y))   # x/y
print(np.sqrt(x))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [68]:
# matrix multiplication and dot products
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [69]:
# multiplication(Dot Product) of vectors gives us a scalar
a = np.array([1,2,3,4])
b = np.array([5,6,6,7])
print(a.dot(b))

63


In [70]:
print(a)
print(sum(a))

print(x)
print(np.sum(x))
print(np.sum(x,axis = 1)) #takes sum across the axis
print(np.sum(x, axis = 0))

[1 2 3 4]
10
[[1 2]
 [3 4]]
10
[3 7]
[4 6]


In [71]:
#stacking of arrays
print(a)
b = b**2
print(b)

print(np.stack((a,b),axis =1))

print(np.stack((a,b),axis =0))

[1 2 3 4]
[25 36 36 49]
[[ 1 25]
 [ 2 36]
 [ 3 36]
 [ 4 49]]
[[ 1  2  3  4]
 [25 36 36 49]]


In [81]:
#reshape a numpy array
a1 = np.stack((a,b),axis =0)
a1 = a1.reshape((8,1))
print(a1)

a1 = a1.reshape((4,2))
print(a1)

a1 = a1.reshape((-1,4))
print(a1)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [25]
 [36]
 [36]
 [49]]
[[ 1  2]
 [ 3  4]
 [25 36]
 [36 49]]
[[ 1  2  3  4]
 [25 36 36 49]]
