## Statistics Function

min, max
mean
median
average
variance
standard deviation

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
print(np.min(a))
print(np.min(a, axis =0))
print(np.min(a, axis =1))

1
[1 2 3]
[1 4]


In [4]:
b = np.array([8,9,7,10])
print(b)
print(np.mean(b))
print(np.mean(a, axis =0))

[ 8  9  7 10]
8.5
[2.5 3.5 4.5]


In [6]:
c = np.array([10,20,30,40,50])
print(c)
print(np.median(c))

# mean vs average is weighted
print("mean ", np.mean(c))

#weights
w = np.array([1,1,2,4,1])
print(np.average(c,weights=w))


[10 20 30 40 50]
30.0
mean  30.0
33.333333333333336


In [7]:
# standard Deviation
dev = np.std(c)
print(dev)

#variance
print(np.var(c))


14.142135623730951
200.0
