## Functions-

rand:    Random values in a given stage
randn:   Return a sample (or samples) from the "standard normal" distribution.
randint: return random integers from low(inclusive) to high (exclusive)
random:  return random floats in the half-open interval [0.0, 1.0]
choice:  generates a random sample from a given 1-D array
shuffle: Shuffles the contents of a sequence

In [17]:
import numpy as np

In [18]:
a = np.arange(10) + 5
print(a)

b = np.arange(10)
print(b)

[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4 5 6 7 8 9]


In [50]:
#shuffling
# np.random.seed(a)   # is is used for creating a series
np.random.shuffle(a)
print(a)

[7 6 5]


In [20]:
c = np.random.rand(2,3)
print(c)

[[0.89337024 0.04242914 0.89928814]
 [0.60946245 0.06467059 0.68335861]]


In [21]:
c = np.random.randn(2,3)
print(c)

[[-1.15977328  1.06590572 -0.60238276]
 [-1.43979788 -1.04911637  1.56059189]]


In [29]:
a = np.random.randint(5,10,3) #(starting digit, ending digit, total numbers)
a

array([5, 7, 6])

In [46]:
element = np.random.choice(b)
element

7